### PR TITLE
chore(CI): fix CI

### PR DESCRIPTION
**Pull request by miraclx**
fix CI

### CODE REVIEW

**Review by MatejVukosav — APPROVED** [review]

**Comment by miraclx** [comment]
Tests seem borked 🫠 

cc: @MatejVukosav, have you observed this kind of issue?

Tried to check to make sure we weren't stuck in an infinite loop, doesn't seem to be the case, but the logs are also gone

**Comment by miraclx** [comment]
Merging anyway as a fix to master, will continue investigating the actions runner issue

**Comment by MatejVukosav** [comment]
> Tests seem borked 🫠 Runs for 44m after which it's killed, or something?
> 
> cc: @MatejVukosav, have you observed this kind of issue?
> 
> Tried to check to make sure we weren't stuck in an infinite loop, doesn't seem to be the case, but the logs are also gone

Not so far. They were much much faster before these new changes

**Comment by MatejVukosav** [comment]
Issue is with memory "You are running out of disk space. The runner will stop working when the machine runs out of disk space."

**Comment by miraclx** [comment]
Yeah, I've nuked the cache, it was bordering on 4GiB of space, should work now.

**Comment by miraclx** [comment]
Yep, we're back in the green

https://github.com/calimero-network/core/commit/cc3dbc6819e64619c260c72f7fafc3035f150971

**Pull request merged**
