### PR TITLE
chore: cargo format

### PR DESCRIPTION
**Pull request by fbozic**
Run `cargo +nightly fmt`.
We should probably automate this check.

### CODE REVIEW

**Comment by MatejVukosav** [comment]
https://github.com/calimero-network/core/blob/43782e39cb563927dfa346bd5e3de28d2f64440e/.github/actions/style/action.yml#L26

**Comment by MatejVukosav** [comment]
> So it doesn't work @MatejVukosav?
> 
> I think these changes are valid from our formatting config POV.

Seems it got broken in the last few weeks

**Review by chefsale — APPROVED** [review]
Create a task for automation

**Comment by MatejVukosav** [comment]
I'll take a look into CI. Merging this.

**Pull request merged**
